name: 'Build test and release'
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      checks: write

    steps:

    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v5
      with:
        cache: 'npm'
        node-version: 20
        registry-url: 'https://registry.npmjs.org'

    - run: npm ci

    - run: npm run test
      name: 'Run the tests'

    - uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3 # v2.1.1
      if: success() || failure()
      name: Tests report
      with:
        name: Tests report
        path: 'reports/jest-*.xml'
        reporter: jest-junit

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0
        id: release
        with:
          release-type: node
      - uses: actions/checkout@v5
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}

