name: Renovate update dependencies
on:
  schedule:
    # UTC 10:00 PM Sunday - Thursday (AEST 8:00 AM, Monday - Friday)
    - cron: "0 22 * * 0-4"
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run"
        required: false
        default: true
        type: boolean

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Renovate
        uses: renovatebot/github-action@22e0a16091fc706b04affe6ae53d5e3358ac4023 # v46.1.19
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
        env:
          RENOVATE_DRY_RUN: ${{ inputs.dry-run && 'full' || null }}